# Generated by Django 3.0.7 on 2021-08-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0002_auto_20210818_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Questions',
        ),
    ]
