# Generated by Django 3.0.7 on 2021-08-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0004_auto_20210819_0659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question_table',
        ),
    ]
