# Generated by Django 3.0.7 on 2021-08-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0007_remove_question_questionsid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
