# Generated by Django 3.0.7 on 2021-08-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GradeID', models.CharField(max_length=10)),
                ('Grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionsId', models.CharField(max_length=10)),
                ('QuestionsText', models.CharField(max_length=100, null=True)),
                ('GradeId', models.CharField(max_length=10)),
                ('Grade', models.CharField(max_length=20, null=True)),
                ('SubjectID', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectID', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=50)),
            ],
        ),
    ]
