# Generated by Django 3.0.7 on 2021-08-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='Grade',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='grade',
            name='GradeID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='Grade',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='GradeId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='QuestionsId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='Subject',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='SubjectID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Subject',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject',
            name='SubjectID',
            field=models.CharField(max_length=100),
        ),
    ]
