# Generated by Django 3.0.7 on 2021-08-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0006_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='QuestionsId',
        ),
    ]
