# Generated by Django 3.0.7 on 2021-08-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0009_question'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='assignment1_question',
        ),
    ]
