# Generated by Django 3.0.7 on 2021-08-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0010_auto_20210819_1323'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
